### ISSUE TITLE
[Feature Request] add leave/invite link guild button on guild_log embed

### ISSUE THREAD

**Issue by gamer50082** [adh319/Lunox#33]
[+] Leave Guild button
[+] invite link to guild

Also I am using GitHub mobile app that why feature request template can't be used

**Comment by ukcai696969** [comment]
why do you mean by ‘invite link to guild’?

**Comment by gamer50082** [comment]
2 diff feature

**Comment by gamer50082** [comment]
Invite to guild and leave guild buttons

**Comment by ukcai696969** [comment]
the invite to guild command is ez

**Comment by gamer50082** [comment]
Leave guild?

**Comment by ukcai696969** [comment]
dunno how to make that

**Comment by gamer50082** [comment]
Check milrato lavamusic

**Comment by gamer50082** [comment]
My bad it's 

https://github.com/Tomato6966/Multipurpose-discord-bot/blob/main/commands/%F0%9F%91%91%20Owner/leaveserver.js

**Comment by adh319** [comment]
look guy,s here what i thought about this project. since this project is free to use for everyone that means u can do anything about it, like adding or removing features. It doesn't need to be me to add the features, i mean what i wanna add will be added to this project and if u wanna add something new u can add it too. either u wanna contribute or not.

**Comment by adh319** [comment]
Solved here https://github.com/adh319/Lunox/commit/ad1df520942a03efd0350375495458014c085352
