### ISSUE TITLE
Bug After Change voice channel location

### ISSUE THREAD

**Issue by KARONAGAMING** [adh319/Lunox#72]
### Bug description

this bug is :
bot stop play music after change channel location and the Lunox bot also bug

### Step to reproduce

same as i say before

### Operating system

Windows 10

### Nodejs version

20.9.0

**Comment by adh319** [comment]
The music stopping after changing the channel is not a bug. It's a common occurrence when using Lavalink because Lavalink can only connect to one location at the same time. Therefore, it will disconnect or destroy the bot from the voice channel.

Regarding the Lunox bot and the bug you mentioned, could you provide more details about the issue? Please explain the problem further.

**Comment by KARONAGAMING** [comment]
Ight thanks

**Comment by KARONAGAMING** [comment]
here video: https://youtu.be/MyOZA9aXVi4

**Comment by adh319** [comment]
I'll try to find the solution for it

**Comment by KARONAGAMING** [comment]
oke thanks <33

**Comment by adh319** [comment]
> oke thanks <33

Since its not a bug and i've asked the poru dev about this. The only way to solve this is call the player pause/resume function for example if you change the voice the region you can just use `/resume` command or press the play/resume button.

**Comment by KARONAGAMING** [comment]
> > oke thanks <33
> 
> Since its not a bug and i've asked the poru dev about this. The only way to solve this is call the player pause/resume function for example if you change the voice the region you can just use `/resume` command or press the play/resume button.

Oke sir Thanks For help.
